/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.shinntl.laptopstore.views.user;

import com.shinntl.laptopstore.constant.SystemConstant;
import com.shinntl.laptopstore.controller.user.HomeController;
import com.shinntl.laptopstore.utils.HashTableUtil;
import com.shinntl.laptopstore.views.LoginJFrame;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author shinn
 */
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    List<JLabel> listName;
    List<JLabel> listPrice;
    List<JButton> listMoreInfor;
    List<JButton> listAddToCartBtn;
    List<JButton> listBuyBtn;
    List<JPanel> listPanel;
    List<JLabel> listImage;

    public HomeJFrame() {
        initComponents();
        setVisible(true);
        addToList();
        ActionListener action = new HomeController(this);
        searchBtn.addActionListener(action);
        preBtn.addActionListener(action);
        nextBtn.addActionListener(action);
        cartPanel.setVisible(false);
        homePanel.setVisible(true);

        removeCartBtn.addActionListener(action);
        buyCartBtn.addActionListener(action);
        removeOrderBtn.addActionListener(action);
        updateOrderBtn.addActionListener(action);
        for (int i = 0; i < listMoreInfor.size(); i++) {
            listMoreInfor.get(i).addActionListener(action);
        }
        for (int i = 0; i < listAddToCartBtn.size(); i++) {
            listAddToCartBtn.get(i).addActionListener(action);
        }
        MouseListener mouseListener = (MouseListener) action;
        cartTable.addMouseListener(mouseListener);
        logoutLabel.addMouseListener(mouseListener);
        homeLabel.addMouseListener(mouseListener);
        cartLabel.addMouseListener(mouseListener);
        orderLabel.addMouseListener(mouseListener);
        filterBtn.addActionListener(action);
        bestSellerBtn.addActionListener(action);
        designTabel(orderTable);
        designTabel(cartTable);
    }

    public void designTabel(JTable jtable) {
        jtable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jtable.getTableHeader().setOpaque(false);
        jtable.getTableHeader().setBackground(new Color(0, 178, 191));
        jtable.getTableHeader().setForeground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        homeLabel = new javax.swing.JLabel();
        cartLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        orderLabel = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cartPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameCartLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripCartTextArea = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        priceCartLabel = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        brandCartLabel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        amountCartLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        imgCartLabel = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        amountInputTf = new javax.swing.JTextField();
        buyCartBtn = new javax.swing.JButton();
        removeCartBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        homePanel = new javax.swing.JPanel();
        preBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        searchTf = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        productPanel1 = new javax.swing.JPanel();
        buyBtn1 = new javax.swing.JButton();
        addToCartBtn1 = new javax.swing.JButton();
        productNameLabel1 = new javax.swing.JLabel();
        priceLabel1 = new javax.swing.JLabel();
        imageProduct1 = new javax.swing.JLabel();
        moreBtn1 = new javax.swing.JButton();
        productPanel2 = new javax.swing.JPanel();
        imageProduct2 = new javax.swing.JLabel();
        productNameLabel2 = new javax.swing.JLabel();
        priceLabel2 = new javax.swing.JLabel();
        buyBtn2 = new javax.swing.JButton();
        addToCartBtn2 = new javax.swing.JButton();
        moreBtn2 = new javax.swing.JButton();
        productPanel3 = new javax.swing.JPanel();
        productNameLabel3 = new javax.swing.JLabel();
        priceLabel3 = new javax.swing.JLabel();
        buyBtn3 = new javax.swing.JButton();
        addToCartBtn3 = new javax.swing.JButton();
        imageProduct3 = new javax.swing.JLabel();
        moreBtn3 = new javax.swing.JButton();
        productPanel4 = new javax.swing.JPanel();
        buyBtn4 = new javax.swing.JButton();
        addToCartBtn4 = new javax.swing.JButton();
        priceLabel4 = new javax.swing.JLabel();
        productNameLabel4 = new javax.swing.JLabel();
        imageProduct4 = new javax.swing.JLabel();
        moreBtn4 = new javax.swing.JButton();
        sortByFilterCb = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        bestSellerBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        sortNameFilterCb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        brandFilterCb = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        filterBtn = new javax.swing.JButton();
        purchasedPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        removeOrderBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        amountOrderTf = new javax.swing.JTextField();
        updateOrderBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        menuPanel.setBackground(new java.awt.Color(0, 51, 153));
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Laptop Store");
        menuPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 162, 34));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shinntl/laptopstore/icons/icons8-laptop-40.png"))); // NOI18N
        menuPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        logoutLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setText("Logout");
        logoutLabel.setToolTipText("");
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });
        menuPanel.add(logoutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 690, 65, 37));

        homeLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        homeLabel.setForeground(new java.awt.Color(255, 255, 255));
        homeLabel.setText("Home");
        homeLabel.setToolTipText("");
        homeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLabelMouseClicked(evt);
            }
        });
        menuPanel.add(homeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 65, 37));

        cartLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        cartLabel.setForeground(new java.awt.Color(255, 255, 255));
        cartLabel.setText("Cart");
        cartLabel.setToolTipText("");
        cartLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartLabelMouseClicked(evt);
            }
        });
        menuPanel.add(cartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 60, 37));
        menuPanel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 180, 10));
        menuPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 180, 10));
        menuPanel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 180, 10));

        orderLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        orderLabel.setForeground(new java.awt.Color(255, 255, 255));
        orderLabel.setText("Order");
        orderLabel.setToolTipText("");
        orderLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                orderLabelMouseClicked(evt);
            }
        });
        menuPanel.add(orderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, 37));
        menuPanel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 180, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shinntl/laptopstore/icons/icons8-close-30 (1).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        menuPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.CardLayout());

        cartPanel.setBackground(new java.awt.Color(255, 255, 255));
        cartPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cartTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Description", "Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        cartTable.setRowHeight(35);
        cartTable.setSelectionBackground(new java.awt.Color(85, 85, 85));
        cartTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(cartTable);

        cartPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 16, 1215, 300));

        jLabel5.setText("Name:");
        cartPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 340, 56, 28));

        jLabel6.setText("Description:");
        cartPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 386, -1, -1));

        nameCartLabel.setText("name here");
        cartPanel.add(nameCartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 345, -1, -1));

        descripCartTextArea.setColumns(20);
        descripCartTextArea.setRows(5);
        jScrollPane2.setViewportView(descripCartTextArea);

        cartPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 386, 236, 125));

        jLabel12.setText("Price:");
        cartPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 62, -1));

        priceCartLabel.setText("Price here");
        cartPanel.add(priceCartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, -1, -1));

        jLabel14.setText("Brand:");
        cartPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, -1, -1));

        brandCartLabel.setText("Brand here");
        cartPanel.add(brandCartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, -1, -1));

        jLabel16.setText("Amount:");
        cartPanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        amountCartLabel.setText("Amount here");
        cartPanel.add(amountCartLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgCartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgCartLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
        );

        cartPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 356, 330, -1));

        jLabel19.setText("Amount to buy:");
        cartPanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 430, 110, 30));
        cartPanel.add(amountInputTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 430, 210, 30));

        buyCartBtn.setBackground(new java.awt.Color(0, 51, 153));
        buyCartBtn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        buyCartBtn.setForeground(new java.awt.Color(255, 255, 255));
        buyCartBtn.setText("Buy ");
        cartPanel.add(buyCartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, 180, 40));

        removeCartBtn.setBackground(new java.awt.Color(0, 0, 0));
        removeCartBtn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        removeCartBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeCartBtn.setText("Remove");
        cartPanel.add(removeCartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 500, 180, 40));
        cartPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 1100, 10));

        jPanel3.add(cartPanel, "card3");

        homePanel.setBackground(new java.awt.Color(255, 255, 255));
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        preBtn.setBackground(new java.awt.Color(0, 0, 204));
        preBtn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        preBtn.setForeground(new java.awt.Color(255, 255, 255));
        preBtn.setText("Previous");
        homePanel.add(preBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 600, 129, 32));

        nextBtn.setBackground(new java.awt.Color(0, 0, 204));
        nextBtn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        nextBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextBtn.setText("Next");
        homePanel.add(nextBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 600, 117, 32));
        homePanel.add(searchTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 434, 39));

        searchBtn.setBackground(new java.awt.Color(0, 51, 255));
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        homePanel.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 6, 126, 39));

        buyBtn1.setBackground(new java.awt.Color(153, 0, 0));
        buyBtn1.setForeground(new java.awt.Color(255, 255, 255));
        buyBtn1.setText("Buy");

        addToCartBtn1.setBackground(new java.awt.Color(0, 0, 255));
        addToCartBtn1.setForeground(new java.awt.Color(255, 255, 255));
        addToCartBtn1.setText("Add to cart");

        productNameLabel1.setText("Name here");

        priceLabel1.setText("Price");

        moreBtn1.setBackground(new java.awt.Color(0, 0, 0));
        moreBtn1.setForeground(new java.awt.Color(255, 255, 255));
        moreBtn1.setText("More");

        javax.swing.GroupLayout productPanel1Layout = new javax.swing.GroupLayout(productPanel1);
        productPanel1.setLayout(productPanel1Layout);
        productPanel1Layout.setHorizontalGroup(
            productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(productNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageProduct1, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGroup(productPanel1Layout.createSequentialGroup()
                        .addComponent(moreBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addToCartBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buyBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        productPanel1Layout.setVerticalGroup(
            productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(imageProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel1)
                .addGap(18, 18, 18)
                .addGroup(productPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addToCartBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(moreBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(buyBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        homePanel.add(productPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 400));

        productNameLabel2.setText("Name here");

        priceLabel2.setText("Price");

        buyBtn2.setBackground(new java.awt.Color(153, 0, 0));
        buyBtn2.setForeground(new java.awt.Color(255, 255, 255));
        buyBtn2.setText("Buy");

        addToCartBtn2.setBackground(new java.awt.Color(0, 0, 255));
        addToCartBtn2.setForeground(new java.awt.Color(255, 255, 255));
        addToCartBtn2.setText("Add to cart");

        moreBtn2.setBackground(new java.awt.Color(0, 0, 0));
        moreBtn2.setForeground(new java.awt.Color(255, 255, 255));
        moreBtn2.setText("More");

        javax.swing.GroupLayout productPanel2Layout = new javax.swing.GroupLayout(productPanel2);
        productPanel2.setLayout(productPanel2Layout);
        productPanel2Layout.setHorizontalGroup(
            productPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanel2Layout.createSequentialGroup()
                .addGroup(productPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(productPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(priceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(productPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imageProduct2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(productPanel2Layout.createSequentialGroup()
                                .addGroup(productPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buyBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(productPanel2Layout.createSequentialGroup()
                                        .addComponent(moreBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addToCartBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))))
                .addGap(17, 17, 17))
        );
        productPanel2Layout.setVerticalGroup(
            productPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(imageProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(productNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(productPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addToCartBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moreBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buyBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        homePanel.add(productPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, 400));

        productNameLabel3.setText("Name here");

        priceLabel3.setText("Price");

        buyBtn3.setBackground(new java.awt.Color(153, 0, 0));
        buyBtn3.setForeground(new java.awt.Color(255, 255, 255));
        buyBtn3.setText("Buy");

        addToCartBtn3.setBackground(new java.awt.Color(0, 0, 255));
        addToCartBtn3.setForeground(new java.awt.Color(255, 255, 255));
        addToCartBtn3.setText("Add to cart");

        moreBtn3.setBackground(new java.awt.Color(0, 0, 0));
        moreBtn3.setForeground(new java.awt.Color(255, 255, 255));
        moreBtn3.setText("More");

        javax.swing.GroupLayout productPanel3Layout = new javax.swing.GroupLayout(productPanel3);
        productPanel3.setLayout(productPanel3Layout);
        productPanel3Layout.setHorizontalGroup(
            productPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanel3Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(productPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanel3Layout.createSequentialGroup()
                        .addGroup(productPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productNameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(productPanel3Layout.createSequentialGroup()
                                .addComponent(moreBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addToCartBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buyBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanel3Layout.createSequentialGroup()
                        .addComponent(imageProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        productPanel3Layout.setVerticalGroup(
            productPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(imageProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productNameLabel3)
                .addGap(18, 18, 18)
                .addComponent(priceLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addToCartBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moreBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buyBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        homePanel.add(productPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, 400));

        buyBtn4.setBackground(new java.awt.Color(153, 0, 0));
        buyBtn4.setForeground(new java.awt.Color(255, 255, 255));
        buyBtn4.setText("Buy");

        addToCartBtn4.setBackground(new java.awt.Color(0, 0, 204));
        addToCartBtn4.setForeground(new java.awt.Color(255, 255, 255));
        addToCartBtn4.setText("Add to cart");

        priceLabel4.setText("Price");

        productNameLabel4.setText("Name here");

        moreBtn4.setBackground(new java.awt.Color(0, 0, 0));
        moreBtn4.setForeground(new java.awt.Color(255, 255, 255));
        moreBtn4.setText("More");
        moreBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productPanel4Layout = new javax.swing.GroupLayout(productPanel4);
        productPanel4.setLayout(productPanel4Layout);
        productPanel4Layout.setHorizontalGroup(
            productPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanel4Layout.createSequentialGroup()
                .addGroup(productPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(productPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(imageProduct4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(productPanel4Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(productPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, productPanel4Layout.createSequentialGroup()
                                .addComponent(moreBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addToCartBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, productPanel4Layout.createSequentialGroup()
                                .addGroup(productPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buyBtn4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(productNameLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE)))))
                .addGap(18, 18, 18))
        );
        productPanel4Layout.setVerticalGroup(
            productPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(imageProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productNameLabel4)
                .addGap(20, 20, 20)
                .addComponent(priceLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(productPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moreBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToCartBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buyBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        homePanel.add(productPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 290, 400));

        sortByFilterCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose option", "Name", "Price" }));
        homePanel.add(sortByFilterCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 160, 40));

        jLabel7.setText("Sort by:");
        homePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 60, 40));

        bestSellerBtn.setBackground(new java.awt.Color(255, 0, 0));
        bestSellerBtn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        bestSellerBtn.setForeground(new java.awt.Color(255, 255, 255));
        bestSellerBtn.setText("Best seller");
        bestSellerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestSellerBtnActionPerformed(evt);
            }
        });
        homePanel.add(bestSellerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 100, 120, 40));

        jLabel8.setText("Sort name:");
        homePanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        sortNameFilterCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose option", "Desc", "Asc" }));
        homePanel.add(sortNameFilterCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 140, 40));

        jLabel9.setText("Brand:");
        homePanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 50, 30));

        brandFilterCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose option" }));
        homePanel.add(brandFilterCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 170, 40));

        jLabel13.setText("Filter Box:");
        homePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 80, 30));

        filterBtn.setBackground(new java.awt.Color(0, 0, 0));
        filterBtn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        filterBtn.setForeground(new java.awt.Color(255, 255, 255));
        filterBtn.setText("Filter");
        homePanel.add(filterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 130, 40));

        jPanel3.add(homePanel, "card2");

        purchasedPanel.setBackground(new java.awt.Color(255, 255, 255));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "OrderID", "Product", "Price", "Amount", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Long.class, java.lang.Integer.class, java.lang.Long.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        orderTable.setRowHeight(35);
        orderTable.setSelectionBackground(new java.awt.Color(85, 85, 85));
        orderTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        orderTable.setShowGrid(false);
        jScrollPane3.setViewportView(orderTable);
        if (orderTable.getColumnModel().getColumnCount() > 0) {
            orderTable.getColumnModel().getColumn(0).setResizable(false);
            orderTable.getColumnModel().getColumn(1).setResizable(false);
            orderTable.getColumnModel().getColumn(2).setResizable(false);
            orderTable.getColumnModel().getColumn(3).setResizable(false);
            orderTable.getColumnModel().getColumn(4).setResizable(false);
        }

        removeOrderBtn.setBackground(new java.awt.Color(0, 0, 0));
        removeOrderBtn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        removeOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        removeOrderBtn.setText("Remove");

        jLabel3.setText("Amount: ");

        updateOrderBtn.setBackground(new java.awt.Color(0, 51, 153));
        updateOrderBtn.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        updateOrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateOrderBtn.setText("Update");

        javax.swing.GroupLayout purchasedPanelLayout = new javax.swing.GroupLayout(purchasedPanel);
        purchasedPanel.setLayout(purchasedPanelLayout);
        purchasedPanelLayout.setHorizontalGroup(
            purchasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasedPanelLayout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(removeOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(updateOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(360, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purchasedPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountOrderTf, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purchasedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        purchasedPanelLayout.setVerticalGroup(
            purchasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purchasedPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(purchasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(amountOrderTf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(purchasedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purchasedPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(updateOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(purchasedPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(removeOrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );

        jPanel3.add(purchasedPanel, "card4");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel10.setText("LAPTOP STORE");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/shinntl/laptopstore/icons/icons8-menu-35.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 415, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1264, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        openMenuBar();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void moreBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreBtn4ActionPerformed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked

    }//GEN-LAST:event_logoutLabelMouseClicked

    private void homeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_homeLabelMouseClicked

    private void cartLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cartLabelMouseClicked

    private void orderLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_orderLabelMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        closeMenuBar();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void bestSellerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestSellerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bestSellerBtnActionPerformed

    // Width: 261.
    public void openMenuBar() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i < 261; i++) {
                    menuPanel.setSize(i, 1264);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    public void closeMenuBar() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 261; i >= 0; i--) {
                    menuPanel.setSize(i, 1264);
                    try {
                        Thread.sleep(2);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(HomeJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }).start();
    }

    public void addToList() {
        listPanel = new ArrayList<>();
        listPanel.add(productPanel1);
        listPanel.add(productPanel2);
        listPanel.add(productPanel3);
        listPanel.add(productPanel4);
        listName = new ArrayList<>();
        listName.add(productNameLabel1);
        listName.add(productNameLabel2);
        listName.add(productNameLabel3);
        listName.add(productNameLabel4);
        listPrice = new ArrayList<>();
        listPrice.add(priceLabel1);
        listPrice.add(priceLabel2);
        listPrice.add(priceLabel3);
        listPrice.add(priceLabel4);
        listMoreInfor = new ArrayList<>();
        listMoreInfor.add(moreBtn1);
        listMoreInfor.add(moreBtn2);
        listMoreInfor.add(moreBtn3);
        listMoreInfor.add(moreBtn4);
        listImage = new ArrayList<>();
        listImage.add(imageProduct1);
        listImage.add(imageProduct2);
        listImage.add(imageProduct3);
        listImage.add(imageProduct4);
        listBuyBtn = new ArrayList<>();
        listBuyBtn.add(buyBtn1);
        listBuyBtn.add(buyBtn2);
        listBuyBtn.add(buyBtn3);
        listBuyBtn.add(buyBtn4);
        listAddToCartBtn = new ArrayList<>();
        listAddToCartBtn.add(addToCartBtn1);
        listAddToCartBtn.add(addToCartBtn2);
        listAddToCartBtn.add(addToCartBtn3);
        listAddToCartBtn.add(addToCartBtn4);
        for (int i = 0; i < listPanel.size(); i++) {
            listPanel.get(i).setVisible(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCartBtn1;
    private javax.swing.JButton addToCartBtn2;
    private javax.swing.JButton addToCartBtn3;
    private javax.swing.JButton addToCartBtn4;
    private javax.swing.JLabel amountCartLabel;
    private javax.swing.JTextField amountInputTf;
    private javax.swing.JTextField amountOrderTf;
    private javax.swing.JButton bestSellerBtn;
    private javax.swing.JLabel brandCartLabel;
    private javax.swing.JComboBox<String> brandFilterCb;
    private javax.swing.JButton buyBtn1;
    private javax.swing.JButton buyBtn2;
    private javax.swing.JButton buyBtn3;
    private javax.swing.JButton buyBtn4;
    private javax.swing.JButton buyCartBtn;
    private javax.swing.JLabel cartLabel;
    private javax.swing.JPanel cartPanel;
    private javax.swing.JTable cartTable;
    private javax.swing.JTextArea descripCartTextArea;
    private javax.swing.JButton filterBtn;
    private javax.swing.JLabel homeLabel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JLabel imageProduct1;
    private javax.swing.JLabel imageProduct2;
    private javax.swing.JLabel imageProduct3;
    private javax.swing.JLabel imageProduct4;
    private javax.swing.JLabel imgCartLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton moreBtn1;
    private javax.swing.JButton moreBtn2;
    private javax.swing.JButton moreBtn3;
    private javax.swing.JButton moreBtn4;
    private javax.swing.JLabel nameCartLabel;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JTable orderTable;
    private javax.swing.JButton preBtn;
    private javax.swing.JLabel priceCartLabel;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JLabel priceLabel2;
    private javax.swing.JLabel priceLabel3;
    private javax.swing.JLabel priceLabel4;
    private javax.swing.JLabel productNameLabel1;
    private javax.swing.JLabel productNameLabel2;
    private javax.swing.JLabel productNameLabel3;
    private javax.swing.JLabel productNameLabel4;
    private javax.swing.JPanel productPanel1;
    private javax.swing.JPanel productPanel2;
    private javax.swing.JPanel productPanel3;
    private javax.swing.JPanel productPanel4;
    private javax.swing.JPanel purchasedPanel;
    private javax.swing.JButton removeCartBtn;
    private javax.swing.JButton removeOrderBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTf;
    private javax.swing.JComboBox<String> sortByFilterCb;
    private javax.swing.JComboBox<String> sortNameFilterCb;
    private javax.swing.JButton updateOrderBtn;
    // End of variables declaration//GEN-END:variables

    public List<JLabel> getListName() {
        return listName;
    }

    public void setListName(List<JLabel> listName) {
        this.listName = listName;
    }

    public List<JLabel> getListPrice() {
        return listPrice;
    }

    public void setListPrice(List<JLabel> listPrice) {
        this.listPrice = listPrice;
    }

    public List<JButton> getListMoreInfor() {
        return listMoreInfor;
    }

    public void setListMoreInfor(List<JButton> listMoreInfor) {
        this.listMoreInfor = listMoreInfor;
    }

    public List<JButton> getListAddToCartBtn() {
        return listAddToCartBtn;
    }

    public void setListAddToCartBtn(List<JButton> listAddToCartBtn) {
        this.listAddToCartBtn = listAddToCartBtn;
    }

    public List<JButton> getListBuyBtn() {
        return listBuyBtn;
    }

    public void setListBuyBtn(List<JButton> listBuyBtn) {
        this.listBuyBtn = listBuyBtn;
    }

    public List<JPanel> getListPanel() {
        return listPanel;
    }

    public void setListPanel(List<JPanel> listPanel) {
        this.listPanel = listPanel;
    }

    public List<JLabel> getListImage() {
        return listImage;
    }

    public void setListImage(List<JLabel> listImage) {
        this.listImage = listImage;
    }

    public JTextField getSearchTf() {
        return searchTf;
    }

    public void setSearchTf(JTextField searchTf) {
        this.searchTf = searchTf;
    }

    public JTable getCartTable() {
        return cartTable;
    }

    public void setCartTable(JTable cartTable) {
        this.cartTable = cartTable;
    }

    public JPanel getCartPanel() {
        return cartPanel;
    }

    public void setCartPanel(JPanel cartPanel) {
        this.cartPanel = cartPanel;
    }

    public JPanel getHomePanel() {
        return homePanel;
    }

    public void setHomePanel(JPanel homePanel) {
        this.homePanel = homePanel;
    }

    public JLabel getAmountCartLabel() {
        return amountCartLabel;
    }

    public void setAmountCartLabel(JLabel amountCartLabel) {
        this.amountCartLabel = amountCartLabel;
    }

    public JTextField getAmountInputTf() {
        return amountInputTf;
    }

    public void setAmountInputTf(JTextField amountInputTf) {
        this.amountInputTf = amountInputTf;
    }

    public JLabel getBrandCartLabel() {
        return brandCartLabel;
    }

    public void setBrandCartLabel(JLabel brandCartLabel) {
        this.brandCartLabel = brandCartLabel;
    }

    public JButton getBuyCartBtn() {
        return buyCartBtn;
    }

    public void setBuyCartBtn(JButton buyCartBtn) {
        this.buyCartBtn = buyCartBtn;
    }

    public JTextArea getDescripCartTextArea() {
        return descripCartTextArea;
    }

    public void setDescripCartTextArea(JTextArea descripCartTextArea) {
        this.descripCartTextArea = descripCartTextArea;
    }

    public JLabel getImgCartLabel() {
        return imgCartLabel;
    }

    public void setImgCartLabel(JLabel imgCartLabel) {
        this.imgCartLabel = imgCartLabel;
    }

    public JLabel getPriceCartLabel() {
        return priceCartLabel;
    }

    public void setPriceCartLabel(JLabel priceCartLabel) {
        this.priceCartLabel = priceCartLabel;
    }

    public JButton getRemoveCartBtn() {
        return removeCartBtn;
    }

    public void setRemoveCartBtn(JButton removeCartBtn) {
        this.removeCartBtn = removeCartBtn;
    }

    public JLabel getNameCartLabel() {
        return nameCartLabel;
    }

    public void setNameCartLabel(JLabel nameCartLabel) {
        this.nameCartLabel = nameCartLabel;
    }

    public JLabel getLogoutLabel() {
        return logoutLabel;
    }

    public void setLogoutLabel(JLabel logoutLabel) {
        this.logoutLabel = logoutLabel;
    }

    public JLabel getCartLabel() {
        return cartLabel;
    }

    public void setCartLabel(JLabel cartLabel) {
        this.cartLabel = cartLabel;
    }

    public JLabel getHomeLabel() {
        return homeLabel;
    }

    public void setHomeLabel(JLabel homeLabel) {
        this.homeLabel = homeLabel;
    }

    public JPanel getPurchasedPanel() {
        return purchasedPanel;
    }

    public void setPurchasedPanel(JPanel purchasedPanel) {
        this.purchasedPanel = purchasedPanel;
    }

    public JTextField getAmountOrderTf() {
        return amountOrderTf;
    }

    public void setAmountOrderTf(JTextField amountOrderTf) {
        this.amountOrderTf = amountOrderTf;
    }

    public JButton getPreBtn() {
        return preBtn;
    }

    public void setPreBtn(JButton preBtn) {
        this.preBtn = preBtn;
    }

    public JLabel getOrderLabel() {
        return orderLabel;
    }

    public void setOrderLabel(JLabel orderLabel) {
        this.orderLabel = orderLabel;
    }

    public JTable getOrderTable() {
        return orderTable;
    }

    public void setOrderTable(JTable orderTable) {
        this.orderTable = orderTable;
    }

    public JButton getRemoveOrderBtn() {
        return removeOrderBtn;
    }

    public void setRemoveOrderBtn(JButton removeOrderBtn) {
        this.removeOrderBtn = removeOrderBtn;
    }

    public JButton getUpdateOrderBtn() {
        return updateOrderBtn;
    }

    public void setUpdateOrderBtn(JButton updateOrderBtn) {
        this.updateOrderBtn = updateOrderBtn;
    }

    public JButton getBestSellerBtn() {
        return bestSellerBtn;
    }

    public void setBestSellerBtn(JButton bestSellerBtn) {
        this.bestSellerBtn = bestSellerBtn;
    }

    public JComboBox<String> getBrandFilterCb() {
        return brandFilterCb;
    }

    public void setBrandFilterCb(JComboBox<String> brandFilterCb) {
        this.brandFilterCb = brandFilterCb;
    }

    public JComboBox<String> getSortByFilterCb() {
        return sortByFilterCb;
    }

    public void setSortByFilterCb(JComboBox<String> sortByFilterCb) {
        this.sortByFilterCb = sortByFilterCb;
    }

    public JComboBox<String> getSortNameFilterCb() {
        return sortNameFilterCb;
    }

    public void setSortNameFilterCb(JComboBox<String> sortNameFilterCb) {
        this.sortNameFilterCb = sortNameFilterCb;
    }

}
